### ISSUE TITLE
Improve aesthetics of NumberGuessGame.

### ISSUE THREAD

**Issue by VickyTheRocker** [VickyTheRocker/BeginnerProjects#12]
Add the code to clear the output screen before a new game.
The method to clear the screen must be generic.

**Comment by cack195** [comment]
Hi @VickyTheRocker 
I would like to take this issue and implement the feature.
Please assign me to this issue

**Comment by cack195** [comment]
Hi @VickyTheRocker 
I have submitted PR for this issue #30 
Kindly check and update if any changes needed
